name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main  # 监听 main 分支的推送事件

jobs:
  build-deploy:
    runs-on: ubuntu-22.04  # 使用 Ubuntu 22.04 作为运行环境

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Hugo
      uses: peaceiris/actions-hugo@v2.6.0
      with:
        hugo-version: '0.147.4'  # 请根据您的需要调整 Hugo 版本
        extended: true

    - name: Build site
      run: hugo --minify

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public

